// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BuildTimeHistory
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidBuildTimeHistoryPackageString = "c0e7666d-0fc1-4e88-9c61-0468227a9922";
        public static Guid guidBuildTimeHistoryPackage = new Guid(guidBuildTimeHistoryPackageString);

        public const string guidBuildTimeHistoryPackageCmdSetString = "f26ba28b-b7f1-4327-b20f-ba4aa04e6190";
        public static Guid guidBuildTimeHistoryPackageCmdSet = new Guid(guidBuildTimeHistoryPackageCmdSetString);

        public const string guidImagesString = "e60897d4-cf45-45c0-b5ba-bbcca7dc9e55";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int BuildHistoryWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}