// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BuildTimeHistory
{
    internal sealed partial class Vsix
    {
        public const string Id = "TrackTimeBuilding.14cbbf05-c896-480f-b5dd-c8c55bf5fd6d";
        public const string Name = "Build Time History";
        public const string Description = @"Keep track of the total time spent waiting for code to build.";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Matt Lacey";
        public const string Tags = "";
    }
}
